documenso:

  podAnnotations: {}

  podLabels: {}

  podSecurityContext: {}

  securityContext: {}

  replicaCount: 1
  image:
    repository: documenso/documenso
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  cm:
    # ConfigMap entries
    # This is a map of key-value pairs that will be passed to the ConfigMap
    # You can use this to add additional configuration to your application
    # This is optional and there is no default value
    # cmKey: cmValue
    NEXTAUTH_URL: ""
    NEXT_PRIVATE_ENCRYPTION_KEY: ""
    NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY: ""
    NEXTAUTH_SECRET: ""
    NEXT_PUBLIC_WEBAPP_URL: ""
    NEXT_PUBLIC_MARKETING_URL: ""
    NEXT_PRIVATE_DATABASE_URL: ""
    NEXT_PRIVATE_DIRECT_DATABASE_URL: ""
    NEXT_PRIVATE_SMTP_FROM_NAME: ""
    NEXT_PRIVATE_SMTP_FROM_ADDRESS: ""
    NEXT_PRIVATE_SMTP_HOST: ""
    NEXT_PRIVATE_SMTP_PORT: ""
    NEXT_PRIVATE_SMTP_SECURE: ""
    NEXT_PRIVATE_SMTP_USER: ""
    NEXT_PRIVATE_SMTP_PASS: ""
    NEXT_PRIVATE_GOOGLE_CLIENT_ID: ""
    NEXT_PRIVATE_GOOGLE_CLIENT_SECRET: ""

  imagePullSecrets: []
  namespaceOverride: "documenso"
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: ""


  service:
    type: ClusterIP
    port: 3000

  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

  resources: 
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   memory: 128Mi
    requests:
      memory: 256Mi

  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http

  # Additional volumes on the output Deployment definition.
  volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

  # Additional volumeMounts on the output Deployment definition.
  volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

  nodeSelector: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  tolerations: []

  affinity: {}
