apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "documenso.fullname" . }}
  labels:
    {{- include "documenso.labels" . | nindent 4 }}
spec:
  {{- if not .Values.documenso.autoscaling.enabled }}
  replicas: {{ .Values.documenso.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "documenso.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.documenso.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "documenso.labels" . | nindent 8 }}
        {{- with .Values.documenso.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
        - name: cert-generator
          image: alpine:latest
          command:
            - sh
            - -c
            - |
              apk add --no-cache openssl &&
              mkdir -p /certs &&
              echo "Generating CA certificate..." &&
              openssl req -x509 -newkey rsa:4096 -keyout /certs/ca-key.pem -out /certs/ca-cert.pem -days 365 -nodes -subj "/CN=Documenso CA" &&

              echo "Generating Signing Key..." &&
              openssl genpkey -algorithm RSA -out /certs/signing-key.pem &&

              echo "Generating Signing Certificate Request..." &&
              openssl req -new -key /certs/signing-key.pem -out /certs/signing.csr -subj "/CN=Documenso Signing Cert" &&

              echo "Signing the Certificate with CA..." &&
              openssl x509 -req -in /certs/signing.csr -CA /certs/ca-cert.pem -CAkey /certs/ca-key.pem -CAcreateserial -out /certs/signing-cert.pem -days 365 &&

              echo "Creating PKCS#12 (.p12) format file..." &&
              openssl pkcs12 -export -out /certs/signing-cert.p12 -inkey /certs/signing-key.pem -in /certs/signing-cert.pem -password pass:{{ .Values.documenso.certPassword }} &&

              echo "Setting ownership to documenso:documenso" &&
              chown -R 1001:1001 /certs
          volumeMounts:
            - name: cert-volume
              mountPath: /certs
          
      {{- with .Values.documenso.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "documenso.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.documenso.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.documenso.securityContext | nindent 12 }}
          image: "{{ .Values.documenso.image.repository }}:{{ .Values.documenso.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.documenso.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.documenso.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.documenso.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.documenso.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.documenso.resources | nindent 12 }}
          {{- with .Values.documenso.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: cm-{{ include "documenso.fullname" . }}-app
          volumeMounts:
            - name: cert-volume
              mountPath: /certs
            - name: documenso-storage
              mountPath: /data
      volumes:
        - name: cert-volume
          emptyDir: {}
        {{- if .Values.documenso.persistence.enabled }}
        - name: documenso-storage
          persistentVolumeClaim:
            claimName: {{ include "documenso.fullname" . }}-pvc
        {{- end }}
      {{- with .Values.documenso.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.documenso.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.documenso.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
