apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "documenso.fullname" . }}
  labels:
    {{- include "documenso.labels" . | nindent 4 }}
spec:
  {{- if not .Values.documenso.autoscaling.enabled }}
  replicas: {{ .Values.documenso.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "documenso.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.documenso.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "documenso.labels" . | nindent 8 }}
        {{- with .Values.documenso.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.documenso.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "documenso.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.documenso.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.documenso.securityContext | nindent 12 }}
          image: "{{ .Values.documenso.image.repository }}:{{ .Values.documenso.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.documenso.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.documenso.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.documenso.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.documenso.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.documenso.resources | nindent 12 }}
          {{- with .Values.documenso.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: cm-{{ include "documenso.fullname" . }}-app
      {{- with .Values.documenso.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.documenso.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.documenso.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.documenso.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
