{{- if .Values.documenso.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "documenso.serviceAccountName" . }}
  labels:
    {{- include "documenso.labels" . | nindent 4 }}
  {{- with .Values.documenso.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.documenso.serviceAccount.automount }}
{{- end }}
